CREATE DATABASE IF NOT EXISTS polishsite;

USE polishsite;

CREATE TABLE IF NOT EXISTS users (
     id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(50) NOT NULL,
     surname VARCHAR(50) NOT NULL,
     email VARCHAR(100) NOT NULL UNIQUE,
     password_hash VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS resources (
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    access TEXT NOT NULL,
    link TEXT NULL DEFAULT NULL,
    address TEXT NULL DEFAULT NULL,
    phone TEXT NULL DEFAULT NULL
) ENGINE = InnoDB;